### ISSUE TITLE
Uncaught TypeError: codeBlockManager is undefined

### ISSUE THREAD

**Issue by azmeuk** [leeonfield/editor-plugin-video#9]
Hi. I just tested editor-plugin-video 0.2.1 with toast-ui-editor 3.0.1 and I get this error in my Firefox console:

```
Uncaught TypeError: codeBlockManager is undefined
    videoPlugin toastui-editor-plugin-video.js:139
    videoPlugin toastui-editor-plugin-video.js:138
    execPlugin index.js:19938
    getPluginInfo index.js:19943
    getPluginInfo index.js:19942
    ToastUIEditorCore index.js:20550
    ToastUIEditor index.js:22866
    instance simple.svelte:14
    run$2 index.mjs:18
    mount_component index.mjs:1718
    flush index.mjs:1026
    init$1 index.mjs:1810
    Simple bundle.js:86491
    replaceTargetByComponent bundle.js:29848
    replaceClassByComponent utils.svelte:23
    <anonymous> main.js:4
    <anonymous> bundle.js:86582
```

**Comment by leeonfield** [comment]
got that, fiting the new version now @azmeuk

**Comment by azmeuk** [comment]
I am not sure what you are telling me. I see that the repository has not changed nor any package update has been published. Are you saying you intend to work on this?
Thank you for your time anyway!

**Comment by azmeuk** [comment]
I can see in the migration guide that codeBlockManager have been removed in toastui-editor 3

https://github.com/nhn/tui.editor/blob/master/docs/v3.0-migration-guide.md#3-removed-apis

**Comment by leeonfield** [comment]
> I can see in the migration guide that codeBlockManager have been removed in toastui-editor 3
> 
> https://github.com/nhn/tui.editor/blob/master/docs/v3.0-migration-guide.md#3-removed-apis

yeap, so need another way to build video extension

**Comment by fang2023** [comment]
> > I can see in the migration guide that codeBlockManager have been removed in toastui-editor 3
> > https://github.com/nhn/tui.editor/blob/master/docs/v3.0-migration-guide.md#3-removed-apis
> 
> yeap, so need another way to build video extension

What way

**Comment by azmeuk** [comment]
Hello @leeonfield
How is it fixed? I cannot anything new in the repository.
